# Site settings
title: My Jekyll Site
description: A description of my site
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://example.com" # The base URL of your site

# Build settings
markdown: kramdown
theme: minima # You can use a different theme if desired

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

# Include files and directories in the build
include:
  - _pages

# Permalinks
permalink: pretty

# Other settings
timezone: "UTC"
